name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos:
    name: macOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Build
        run: swift build -v -c release --build-tests
      - name: Run tests
        run: swift test -v -c release --skip-build
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
          - build -c release
          - test -c release
    steps:
      - uses: actions/checkout@v3
      - name: Action
        run: Scripts/ubuntu.sh ${{ matrix.action }}
