name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos:
    name: macOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Restore Swift Package Manager cache
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build -c release --build-tests
      - name: Run tests
        run: swift test -c release --skip-build
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    container: swift:5.7.1
    steps:
      - uses: actions/checkout@v3
      - name: Restore Swift Package Manager cache
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build -c release --build-tests
      - name: Run tests
        run: swift test -c release --skip-build
